server:
  port: 9081
  servlet:
    context-path: /api
#jwt:
#  auth:
#    converter:
#      resource-id: login-app
spring:
  application:
    name: identity
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:18080/realms/moviebrains
  threads:
    virtual:
      enabled: true

keycloak:
  realm: moviebrains
  client-id: identity-app
  client-secret: 8sNojAwDeV9oIf5wHyOr0MT6wi7hZf9J
  client-name: identity-app
  url: 'http://localhost:18080'
logging:
  level:
    org.springframework.security: DEBUG